name: Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: library
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build Application e Docker Image (com Jib)
      # O package força o maven a compilar classes, rodar os testes e gerar os binários 
      run: mvn package jib:dockerBuild

    - name: Push to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: libraryapi-ecr
        IMAGE_TAG: ${{ github.run_id }}
      run: |
        # Retag da imagem compilada pelo Jib para adicionar a versão única do github actions ($github.run_id) e latest
        docker tag joaotinelli/libraryapi:v3 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag joaotinelli/libraryapi:v3 $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        # O push final no ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition libraryapi-task-definition --query taskDefinition | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .enableFaultInjection)' > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: libraryapi-container
        image: ${{ steps.login-ecr.outputs.registry }}/libraryapi-ecr:${{ github.run_id }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: libraryapi-task-definition-service-sagw3tow
        cluster: libraryapi-cluster
        wait-for-service-stability: true
